# node.yml

name: "Node.js CI"

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  
  install:
    
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        node-version: [ 12 ]
        os: [ "ubuntu-16.04", "ubuntu-latest", "macos-latest" ]
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v2
      
      - name: "Use Node.js ${{ matrix.node-version }}"
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
  
  build:
    
    runs-on: ubuntu-latest
    
    steps:
      
      - name: "Checkout"
        uses: actions/checkout@v2
